# permissions for end users to edit kernelmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kernel-manager-controller
    app.kubernetes.io/managed-by: kustomize
  name: kernelmanager-editor-role
rules:
- apiGroups:
  - jupyrator.org
  resources:
  - kernelmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jupyrator.org
  resources:
  - kernelmanagers/status
  verbs:
  - get
