---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - jupyrator.org
  resources:
  - kernelmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jupyrator.org
  resources:
  - kernelmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - jupyrator.org
  resources:
  - kernelmanagers/status
  verbs:
  - get
  - patch
  - update
