# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/jupyrator.org_kernelmanagers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: kernelmanagers.jupyrator.org
    version: v1
  path: ./patches/additional_columns_patches.yaml
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: kernelmanagers.jupyrator.org
    version: v1
  path: ./patches/validation_patches.yaml
