name: Build & Publish KernelManager Controller Docker image

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

env:
  REGISTRY: ${{ github.repository }}
  IMAGE: kernel-manager-controller
  TAG: ${{ github.event.release.tag_name }}

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push multi-arch docker image on release
      run: |
        export IMG=${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
        make docker-buildx

    - name: Build and push latest multi-arch docker image
      id: latest
      run: |
        export IMG=${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
        make docker-buildx
