name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'config/**'
  pull_request:
    branches:
        - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'config/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI


jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
